import { Search, Sparkles, LockKeyhole } from "lucide-react";
import type { Market, Listing, SearchMode } from "./types";

export const markets: Market[] = [
  {
    id: "france",
    country: "FRANCE",
    city: "Paris",
    title: "TROUVER LE BIEN IDEAL EN QUELQUES SECONDES",
    subtitle: "",
    strapline: "Avec recherche classique ou IA Intelligence",
    note: "Avec recherche classique ou IA Intelligence",
    image: "/images/paris-hero-luxe.png",
    defaultType: "Maison",
    defaultLocation: "Paris",
    stats: { size: "750 M²", beds: "6 SUITES", pool: "INFINITY POOL" },
  },
  {
    id: "luxembourg",
    country: "LUXEMBOURG",
    city: "Luxembourg",
    title: "TROUVER LE BIEN IDEAL EN QUELQUES SECONDES",
    subtitle: "",
    strapline: "Signature patrimoniale",
    note: "Avec recherche classique ou IA Intelligence",
    image: "/images/luxembourg-hero-luxe.png",
    defaultType: "Penthouse",
    defaultLocation: "",
    stats: { size: "920 M²", beds: "8 SUITES", pool: "POOL" },
  },
  {
    id: "belgium",
    country: "BELGIUM",
    city: "Belgium",
    title: "TROUVER LE BIEN IDEAL EN QUELQUES SECONDES",
    subtitle: "",
    strapline: "Collection confidentielle",
    note: "Avec recherche classique ou IA Intelligence",
    image: "/images/belgium-hero-luxe.png",
    defaultType: "Appartement",
    defaultLocation: "Bruxelles / Uccle / Louise",
    stats: { size: "640 M²", beds: "5 SUITES", pool: "LAP POOL" },
  },
];

export const quickFilters = [
  { key: "appartement-meuble", label: "Appartement meublé" },
  { key: "maison-architecte", label: "Maison d'architecte" },
  { key: "terrain-premium", label: "Terrain" },
  { key: "penthouse", label: "Penthouse" },
  // { key: "investissement-prime", label: "Investissement" },
  { key: "vue-monument", label: "Vue monument" },
];

export const searchModes: {
  id: SearchMode;
  label: string;
  title: string;
  description: string;
  icon: typeof Search;
  action: string;
}[] = [
  {
    id: "classic",
    label: "Recherche classique",
    title: "Formulaire de recherche",
    description:
      "Un formulaire clair pour cibler maison, appartement, terrain ou penthouse avec vos critères essentiels.",
    icon: Search,
    action: "Rechercher un bien",
  },
  {
    id: "ai",
    label: "Recherche avec l'IA",
    title: "Recherche assistée par l'IA",
    description:
      "Décrivez le bien souhaité en langage naturel, et laissez l'IA orienter la sélection la plus pertinente.",
    icon: Sparkles,
    action: "Lancer l'IA",
  },
  {
    id: "offmarket",
    label: "Recherche off-market",
    title: "Mandats confidentiels & off-market",
    description:
      "Accédez à une sélection plus discrète pour les acquéreurs souhaitant des actifs rares hors diffusion publique.",
    icon: LockKeyhole,
    action: "Demander l'accès",
  },
];

export const listings: Listing[] = [
  // ── FRANCE ────────────────────────────────────────────────────────────────
  {
    id: "france-01",
    country: "france",
    title: "Maison Signature Passy",
    district: "Passy",
    type: "Maison",
    price: "12,8 M€",
    surface: "750 m²",
    suites: "6 suites",
    summary:
      "Volumes majestueux, pierre claire, patio planté et perspective ouverte vers un paysage urbain emblématique.",
    tags: ["maison-architecte", "vue-monument"],
    offmarket: false,
    focus: "center",
  },
  {
    id: "france-02",
    country: "france",
    title: "Appartement Alma Collection",
    district: "Triangle d'Or",
    type: "Appartement",
    price: "6,4 M€",
    surface: "312 m²",
    suites: "3 suites",
    summary:
      "Appartement meublé avec marbre clair, salon traversant et finitions de galerie résidentielle.",
    tags: ["appartement-meuble", "investissement-prime"],
    offmarket: false,
    focus: "45% center",
  },
  {
    id: "france-03",
    country: "france",
    title: "Terrain Rare Issy Panorama",
    district: "Ouest parisien",
    type: "Terrain",
    price: "4,1 M€",
    surface: "1 100 m²",
    suites: "Projet libre",
    summary:
      "Parcelle premium pour villa contemporaine avec cadrage soigné sur le skyline et potentiel patrimonial élevé.",
    tags: ["terrain-premium", "vue-monument"],
    offmarket: true,
    focus: "55% center",
  },
  {
    id: "france-04",
    country: "france",
    title: "Villa Neuilly Cour Privée",
    district: "Neuilly-sur-Seine",
    type: "Maison",
    price: "18,5 M€",
    surface: "980 m²",
    suites: "7 suites",
    summary:
      "Hôtel particulier rénové, cour d'honneur pavée, bibliothèque double hauteur et jardin d'hiver vitré.",
    tags: ["maison-architecte", "investissement-prime"],
    offmarket: true,
    focus: "35% center",
  },
  {
    id: "france-05",
    country: "france",
    title: "Penthouse Marais Zénith",
    district: "Le Marais",
    type: "Penthouse",
    price: "9,2 M€",
    surface: "420 m²",
    suites: "4 suites",
    summary:
      "Dernier étage en duplex, toiture-terrasse panoramique, verrières industrielles et finitions sur mesure au cœur historique.",
    tags: ["penthouse", "vue-monument"],
    offmarket: false,
    focus: "center",
  },
  {
    id: "france-06",
    country: "france",
    title: "Résidence Saint-Germain Privée",
    district: "Saint-Germain-des-Prés",
    type: "Appartement",
    price: "7,6 M€",
    surface: "356 m²",
    suites: "4 suites",
    summary:
      "Appartement de caractère au sein d'un immeuble classé, parquets Versailles, boiseries d'époque et cave voutée.",
    tags: ["appartement-meuble", "vue-monument"],
    offmarket: false,
    focus: "50% center",
  },
  {
    id: "france-07",
    country: "france",
    title: "Domaine Fontainebleau Forêt",
    district: "Seine-et-Marne",
    type: "Maison",
    price: "5,3 M€",
    surface: "620 m²",
    suites: "5 suites",
    summary:
      "Demeure de prestige en lisière de forêt, piscine couverte, court de tennis et dépendances rénovées.",
    tags: ["maison-architecte", "terrain-premium"],
    offmarket: false,
    focus: "40% center",
  },
  {
    id: "france-08",
    country: "france",
    title: "Appartement Champs-Élysées Axe",
    district: "8e arrondissement",
    type: "Appartement",
    price: "14,1 M€",
    surface: "485 m²",
    suites: "5 suites",
    summary:
      "Pied-à-terre d'exception sur l'axe triomphal, vue dégagée, sécurité renforcée et services hôteliers intégrés.",
    tags: ["appartement-meuble", "vue-monument", "investissement-prime"],
    offmarket: true,
    focus: "center",
  },

  // ── LUXEMBOURG ────────────────────────────────────────────────────────────
  {
    id: "lux-01",
    country: "luxembourg",
    title: "Penthouse Kirchberg Horizon",
    district: "Kirchberg",
    type: "Penthouse",
    price: "9,7 M€",
    surface: "510 m²",
    suites: "4 suites",
    summary:
      "Dernier étage panoramique, terrasses minérales et signature contemporaine dans un quartier institutionnel premium.",
    tags: ["penthouse", "vue-monument"],
    offmarket: true,
    focus: "center",
  },
  {
    id: "lux-02",
    country: "luxembourg",
    title: "Maison Limpertsberg Atelier",
    district: "Limpertsberg",
    type: "Maison",
    price: "7,9 M€",
    surface: "430 m²",
    suites: "5 suites",
    summary:
      "Maison d'architecte lumineuse, matières nobles, lignes structurales et jardin confidentiel.",
    tags: ["maison-architecte", "investissement-prime"],
    offmarket: false,
    focus: "40% center",
  },
  {
    id: "lux-03",
    country: "luxembourg",
    title: "Appartement Cloche d'Or Privé",
    district: "Cloche d'Or",
    type: "Appartement",
    price: "3,8 M€",
    surface: "245 m²",
    suites: "3 suites",
    summary:
      "Appartement meublé à l'élégance sobre, idéal pied-à-terre de direction ou investissement à haut rendement.",
    tags: ["appartement-meuble", "investissement-prime"],
    offmarket: false,
    focus: "58% center",
  },
  {
    id: "lux-04",
    country: "luxembourg",
    title: "Villa Belair Cascade",
    district: "Belair",
    type: "Maison",
    price: "11,4 M€",
    surface: "720 m²",
    suites: "6 suites",
    summary:
      "Villa contemporaine en retrait de la ville, piscine à débordement, home cinema et accès discret sécurisé.",
    tags: ["maison-architecte", "terrain-premium"],
    offmarket: true,
    focus: "45% center",
  },
  {
    id: "lux-05",
    country: "luxembourg",
    title: "Appartement Merl Signature",
    district: "Merl",
    type: "Appartement",
    price: "4,5 M€",
    surface: "290 m²",
    suites: "3 suites",
    summary:
      "Appartement neuf clé en main, cuisine ouverte sur double séjour, terrasse filante et finitions architecturales soignées.",
    tags: ["appartement-meuble", "investissement-prime"],
    offmarket: false,
    focus: "52% center",
  },
  {
    id: "lux-06",
    country: "luxembourg",
    title: "Penthouse Hollerich Vue Pont",
    district: "Hollerich",
    type: "Penthouse",
    price: "6,8 M€",
    surface: "370 m²",
    suites: "4 suites",
    summary:
      "Penthouse sur toit plat végétalisé, vue sur les viaducs de la vallée de la Pétrusse et intérieur épuré haut de gamme.",
    tags: ["penthouse", "vue-monument"],
    offmarket: false,
    focus: "center",
  },
  {
    id: "lux-07",
    country: "luxembourg",
    title: "Terrain Strassen Confidentiel",
    district: "Strassen",
    type: "Terrain",
    price: "3,2 M€",
    surface: "1 200 m²",
    suites: "Projet sur mesure",
    summary:
      "Rare parcelle constructible dans une enclave résidentielle prisée, viabilisée et prête pour programme villa premium.",
    tags: ["terrain-premium"],
    offmarket: true,
    focus: "60% center",
  },
  {
    id: "lux-08",
    country: "luxembourg",
    title: "Maison Cents Galerie",
    district: "Cents",
    type: "Maison",
    price: "8,9 M€",
    surface: "560 m²",
    suites: "5 suites",
    summary:
      "Architecture cubiste immaculée, murs de verre structurels, galerie d'art intégrée et terrasse-toit avec vue dégagée.",
    tags: ["maison-architecte", "vue-monument"],
    offmarket: false,
    focus: "38% center",
  },

  // ── BELGIUM ───────────────────────────────────────────────────────────────
  {
    id: "bel-01",
    country: "belgium",
    title: "Loft Louise Cristal",
    district: "Avenue Louise",
    type: "Appartement",
    price: "4,9 M€",
    surface: "268 m²",
    suites: "3 suites",
    summary:
      "Loft meublé en verre et métal brossé, volumes ouverts, ambiance galerie et adresse internationale.",
    tags: ["appartement-meuble", "penthouse"],
    offmarket: false,
    focus: "center",
  },
  {
    id: "bel-02",
    country: "belgium",
    title: "Villa Uccle Monolithe",
    district: "Uccle",
    type: "Maison",
    price: "8,2 M€",
    surface: "640 m²",
    suites: "5 suites",
    summary:
      "Villa de réception avec lignes futuristes, palette pierre claire et bassin de nage intégré.",
    tags: ["maison-architecte", "investissement-prime"],
    offmarket: true,
    focus: "50% center",
  },
  {
    id: "bel-03",
    country: "belgium",
    title: "Terrain Waterloo Signature",
    district: "Waterloo",
    type: "Terrain",
    price: "2,7 M€",
    surface: "1 450 m²",
    suites: "Projet sur mesure",
    summary:
      "Terrain premium destiné à une résidence de prestige, dans un environnement verdoyant proche du cœur métropolitain.",
    tags: ["terrain-premium", "vue-monument"],
    offmarket: true,
    focus: "60% center",
  },
  {
    id: "bel-04",
    country: "belgium",
    title: "Penthouse Sablon Collection",
    district: "Le Sablon",
    type: "Penthouse",
    price: "6,1 M€",
    surface: "340 m²",
    suites: "3 suites",
    summary:
      "Penthouse au-dessus du quartier des antiquaires, terrasse minérale, cave à vin et prestations d'hôtel particulier.",
    tags: ["penthouse", "vue-monument"],
    offmarket: false,
    focus: "center",
  },
  {
    id: "bel-05",
    country: "belgium",
    title: "Maison Tervuren Arboretum",
    district: "Tervuren",
    type: "Maison",
    price: "5,6 M€",
    surface: "580 m²",
    suites: "5 suites",
    summary:
      "Demeure de maître en bordure d'arboretum, verrière monumentale, piscine couverte et parc arboré clos de murs.",
    tags: ["maison-architecte", "terrain-premium"],
    offmarket: false,
    focus: "42% center",
  },
  {
    id: "bel-06",
    country: "belgium",
    title: "Appartement Châtelain Prestige",
    district: "Châtelain",
    type: "Appartement",
    price: "3,4 M€",
    surface: "220 m²",
    suites: "3 suites",
    summary:
      "Appartement rénové avec soin dans l'immeuble le plus recherché du quartier, finitions couture et terrasse privative.",
    tags: ["appartement-meuble", "investissement-prime"],
    offmarket: false,
    focus: "55% center",
  },
  {
    id: "bel-07",
    country: "belgium",
    title: "Villa Rhode-Saint-Genèse Blanc",
    district: "Rhode-Saint-Genèse",
    type: "Maison",
    price: "9,8 M€",
    surface: "820 m²",
    suites: "6 suites",
    summary:
      "Villa blanche d'inspiration nordique, espaces de réception exceptionnels, domotique intégrale et forêt en fond de jardin.",
    tags: ["maison-architecte", "investissement-prime"],
    offmarket: true,
    focus: "48% center",
  },
  {
    id: "bel-08",
    country: "belgium",
    title: "Loft Molenbeek Reconversion",
    district: "Molenbeek",
    type: "Appartement",
    price: "2,1 M€",
    surface: "310 m²",
    suites: "2 suites",
    summary:
      "Ancienne imprimerie reconvertie en loft d'exception, charpente métallique apparente, béton ciré et mezzanine bibliothèque.",
    tags: ["appartement-meuble"],
    offmarket: false,
    focus: "center",
  },
];